---
spring:
    rabbitmq:
        host: localhost
        port: 5672
    cloud:
        bus:
            trace:
                enabled: true
    datasource:
        name: dataSource
        url: jdbc:mysql://rm-uf69lhw3233u18lt1o.mysql.rds.aliyuncs.com/p2p_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: p2p
        password: admin123!
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 20
        maxIdle: 20
        minIdle: 0
        initialSize: 1
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 25200000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        maxPoolPreparedStatementPerConnectionSize: 33
        validationQuery: SELECT 1
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        filters: mergeStat
...

---
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/

...
---
mybatis:
    mapperLocations: classpath*:com/newland/financial/p2p/mapping/*-Mapper.xml
...