---
spring:
  profiles: server1
server:
    port: 1111
eureka:
    client:
        serviceUrl:
            defaultZone: http://eurekaserver2:1112/eureka/,http://eurekaserver3:1113/eureka/
    instance:
        #preferIpAddress: true
        hostname: eurekaserver1
...

---
spring:
  profiles: server2
server:
    port: 1112
eureka:
    client:
        serviceUrl:
            defaultZone: http://eurekaserver1:1111/eureka/,http://eurekaserver3:1113/eureka/
    instance:
        #preferIpAddress: true
        hostname: eurekaserver2
...

---
spring:
  profiles: server3
server:
    port: 1113
eureka:
    client:
        serviceUrl:
            defaultZone: http://eurekaserver1:1111/eureka/,http://eurekaserver2:1112/eureka/
    instance:
        #preferIpAddress: true
        hostname: eurekaserver3
...

---
spring:
    application:
        name: "@project.name@"
...

---
eureka:
    instance:
        metadata-map:
            securit:
                user:
                    name: ${security.user.name}
                    password: ${security.user.password}
            management:
                context-path: ${management.context-path}
        statusPageUrl: http://${eureka.instance.hostname}:${server.port}/${management.context-path}/info
        healthCheckUrl: http://${eureka.instance.hostname}:${server.port}/${management.context-path}/health
    server:
        #enable-self-preservation: false
        eviction-interval-timer-in-ms: 4000
    healthcheck:
        enabled: true
    client:
        register-with-eureka: true
        fetch-registry: false
...

---
management:
    security:
        enabled: true
        roles: SUPERUSER
    context-path: /manage
security:
    user:
        name: admin
        password: 123456
    basic:
        enabled: true
        path: ${management.context-path}
...
