---
server:
    port: 1111
...

---
management:
    security:
        enabled: false
...

---
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    instance:
        hostname: localhost
        statusPageUrl: https://${eureka.instance.hostname}/info
        healthCheckUrl: https://${eureka.instance.hostname}/health
        homePageUrl: https://${eureka.instance.hostname}/
    server:
        #enable-self-preservation: false
        eviction-interval-timer-in-ms: 4000
    healthcheck:
        enabled: true

...

