version: '3'
services:
    p2peureka1:
        image: 192.168.10.38:8082/p2p-eureka-server:latest
        networks:
            docker-net:
                aliases:
                   - eurekaserver
                   - eurekaserver1
        ports:
            - "1111:1111"
        environment:
            - spring.profiles.active=server1
            - ADDITIONAL_EUREKA_SERVER_LIST=http://eurekaserver1:1111/eureka/



networks:
    docker-net:
        external:
            name: docker-net