version: '3'
services:
    eurekaserver1:
        image: nexusserver:8082/p2p-eureka-server:latest
        volumes:
            - /home/DockerCommand/:/home/DockerCommand/
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    #cpus: '0.001'
                    memory: 2046M
                reservations:
                    #cpus: '0.0001'
                    memory: 64M
        networks:
            docker-net:
                aliases:
                   - eurekaserver
        ports:
            - "1111:1111"
        environment:
            - spring.profiles.active=server1
            - ADDITIONAL_EUREKA_SERVER_LIST=http://eurekaserver2:1112/eureka/,http://eurekaserver3:1113/eureka/

    eurekaserver2:
        image: nexusserver:8082/p2p-eureka-server:latest
        volumes:
            - /home/DockerCommand/:/home/DockerCommand/
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    #cpus: '0.001'
                    memory: 2046M
                reservations:
                    #cpus: '0.0001'
                    memory: 64M
        networks:
            docker-net:
                aliases:
                   - eurekaserver
        ports:
            - "1112:1111"
        environment:
            - spring.profiles.active=server2
            - ADDITIONAL_EUREKA_SERVER_LIST=http://eurekaserver1:1111/eureka/,http://eurekaserver3:1113/eureka/

    eurekaserver3:
        image: nexusserver:8082/p2p-eureka-server:latest
        volumes:
            - /home/DockerCommand/:/home/DockerCommand/
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    #cpus: '0.001'
                    memory: 2046M
                reservations:
                    #cpus: '0.0001'
                    memory: 64M
        networks:
            docker-net:
                aliases:
                    - eurekaserver
        ports:
            - "1113:1111"
        environment:
            - spring.profiles.active=server3
            - ADDITIONAL_EUREKA_SERVER_LIST=http://eurekaserver1:1111/eureka/,http://eurekaserver2:1112/eureka/

networks:
    docker-net:
        external:
            name: docker-net