version: '3'
services:
    p2pconfig:
        image: nexusserver:8082/p2p-config:latest
        volumes:
            - /home/DockerCommand/:/home/DockerCommand/
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    #cpus: '0.001'
                    memory: 1024M
                reservations:
                    #cpus: '0.0001'
                    memory: 64M
        networks:
            docker-net:
                aliases:
                    - configserver
        ports:
            - "2001:2001"
        environment:
            - SPRING_PROFILES_ACTIVE=test
            - EUREKA_SERVER_ADDRESS=http://eurekaserver:1111/eureka/
            - SERVER_PORT = 2001

    p2padmin:
        image: nexusserver:8082/p2p-admin:latest
        volumes:
            - /home/DockerCommand/:/home/DockerCommand/
        depends_on:
            - p2pconfig
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    #cpus: '0.001'
                    memory: 1024M
                reservations:
                    #cpus: '0.0001'
                    memory: 64M
        networks:
            docker-net:
                aliases:
                    - p2padmin
        ports:
            - "6001:6001"
        environment:
            - SPRING_PROFILES_ACTIVE=test
            - EUREKA_SERVER_ADDRESS=http://eurekaserver:1111/eureka/
            - EUREKA_INSTANCE_HOSTNAME=p2padmin
            - SERVER_PORT = 6001
    p2pturbine:
        image: nexusserver:8082/p2p-turbine:latest
        volumes:
            - /home/DockerCommand/:/home/DockerCommand/
        depends_on:
            - p2pconfig
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    #cpus: '0.001'
                    memory: 1024M
                reservations:
                    #cpus: '0.0001'
                    memory: 64M
        networks:
            docker-net:
                aliases:
                    - p2pturbine
        ports:
            - "6002:6002"
        environment:
            - SPRING_PROFILES_ACTIVE=test
            - EUREKA_SERVER_ADDRESS=http://eurekaserver:1111/eureka/
            - EUREKA_INSTANCE_HOSTNAME=p2pturbine
            - SERVER_PORT = 6002
networks:
    docker-net:
        external:
            name: docker-net