version: '3'
services:
    p2peureka1:
        image: nexusserver:8082/p2p-eureka-server:latest
        volumes:
            - /home/DockerCommand/:/home/DockerCommand/
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    #cpus: '0.001'
                    memory: 2046M
                reservations:
                    #cpus: '0.0001'
                    memory: 64M
        networks:
            docker-net:
                aliases:
                   - eurekaserver
                   - eurekaserver1
        ports:
            - "1111:1111"
        environment:
            - spring.profiles.active=server1
            - ADDITIONAL_EUREKA_SERVER_LIST=http://eurekaserver2:1112/eureka/,http://eurekaserver3:1113/eureka/


networks:
    docker-net:
        external:
            name: docker-net