version: '3'
services:
    p2pschedule:
        image: nexusserver:8082/p2p-schedule:latest
        volumes:
              - /home/smallloan/:/home/smallloan/
              - /home/DockerCommand/:/home/DockerCommand/
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    #cpus: '0.001'
                    memory: 2046M
                reservations:
                    #cpus: '0.0001'
                    memory: 64M
            placement:
                constraints: [node.role == manager]
        networks:
            docker-net:
                aliases:
                    - p2pschedule
        ports:
            - "4002:4002"
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - EUREKA_SERVER_ADDRESS=http://eurekaserver:1111/eureka/
            - SERVER_PORT = 4002


networks:
    docker-net:
        external:
            name: docker-net
