---
spring:
    profiles: dev
    rabbitmq:
        host: 192.168.10.18
        port: 5672
        username: user_admin
        password: admin123%
    redis:
        host: 192.168.10.19
        port: 6379
        database: 0



...

---
spring:
    profiles: test
    rabbitmq:
        host: 10.0.1.42
        port: 5672
        username: user_admin
        password: admin123%
    redis:
        host: 10.0.1.41
        port: 9529
        password: newland123@456!
        database: 0

hystrix:
    threadpool:
        default:
            coreSize: 500
    command:
        default:
            fallback:
                isolation:
                    thread:
                        maxConcurrentRequests: 50
            execution:
                isolation:
                    strategy: thread
                    thread:
                        timeoutInMilliseconds: 10000
                timeout:
                    enabled: false
...

---
spring:
    profiles: prod
    rabbitmq:
        host: 10.0.1.46
        port: 5672
        username: user_admin
        password: admin123%Prod
    redis:
        host: 10.0.1.47
        port: 9529
        password: newland123@456!
        database: 0
...

---
spring:
    cloud:
        bus:
            trace:
                enabled: true
    session:
        store-type: redis
...
