---
spring:
    application:
        name: p2p-api-gateway
    rabbitmq:
        host: localhost
        port: 5672
        cloud:
            bus:
                trace:
                    enabled: true
...

---
zuul:
    addProxyHeaders: true
    routes:
        p2p:
            path: /p2p/**
            sensitiveHeaders: Cookie,Set-Cookie
            serviceId: p2p-client
...

---
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
...

---
ribbon:
    restclient:
        enabled: true
    ConnectTimeout: 3000
    ReadTimeout: 60000
...
