---
spring:
    rabbitmq:
        host: 192.168.10.38
        port: 5672
        username: user_admin
        password: admin123%
    cloud:
        bus:
            trace:
                enabled: true
...

---
zuul:
    addProxyHeaders: true
    routes:
        p2p:
            path: /p2p/**
            sensitiveHeaders: Cookie,Set-Cookie
            serviceId: p2p-client${DEVLOPER_NAME:}
...

---
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
...

---
ribbon:
    restclient:
        enabled: true
    ConnectTimeout: 3000
    ReadTimeout: 60000
...
