---
server:
    port: 5001
...

---
management:
    security:
        enabled: false
...

---
spring:
    application:
        name: p2p-api-gateway
    rabbitmq:
        host: localhost
        port: 5672
        cloud:
            bus:
                trace:
                    enabled: true
...

---
zuul:
    routes:
        p2p:
            path: /p2p/**
            serviceId: p2p-client
...

