---
spring:
    rabbitmq:
        host: 192.168.10.38
        port: 5672
        username: user_admin
        password: admin123%
    cloud:
        bus:
            trace:
                enabled: true
    redis:
        host: 192.168.10.47
        port: 6379
        database: 0
    session:
        store-type: redis
...

---
zuul:
    addProxyHeaders: true
    routes:
        p2p:
            path: /p2p/**
            sensitiveHeaders:
            serviceId: p2p-client${DEVLOPER_NAME:}
...

---
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
...

---
ribbon:
    restclient:
        enabled: true
    ConnectTimeout: 3000
    ReadTimeout: 60000
...

---
spring:
    profiles: dev

appstore:
    masterHost: 51starpos.com
    masterProtocol: https
    address: http://139.224.133.239:7380/server/remote/cxf/slaveMessageService
    #masterHost: 172.16.7.148
    #masterProtocol: http
    #address: http://172.16.7.148:8080/server/remote/cxf/slaveMessageService
...

---
spring:
    profiles: prod

appstore:
    masterHost: starpos.com.cn
    masterProtocol: https
    address: http://192.168.4.19:7380/server/remote/cxf/slaveMessageService
...