---
spring:
    profiles: dev
    rabbitmq:
        host: 192.168.10.38
        port: 5672
        username: user_admin
        password: admin123%
    redis:
        host: 192.168.10.47
        port: 6379
        database: 0
appstore:
    masterHost: 51starpos.com
    masterProtocol: https
    address: http://139.224.133.239:7380/server/remote/cxf/slaveMessageService
...

---
spring:
    profiles: test
    rabbitmq:
        host: 118.31.22.18
        port: 5672
        username: user_admin
        password: admin123%
    redis:
        host: 10.0.1.41
        port: 6379
        database: 0
appstore:
    masterHost: 51starpos.com
    masterProtocol: https
    address: http://139.224.133.239:7380/server/remote/cxf/slaveMessageService
...

---
spring:
    profiles: prod
    rabbitmq:
        host: 10.0.1.46
        port: 5672
        username: user_admin
        password: admin123%Prod
    redis:
        host: 10.0.1.47
        port: 6379
        database: 0
appstore:
    masterHost: starpos.com.cn
    masterProtocol: https
    address: http://192.168.4.19:7380/server/remote/cxf/slaveMessageService
...

---
spring:
    cloud:
        bus:
            trace:
                enabled: true
    session:
        store-type: redis
...

---
zuul:
    addProxyHeaders: true
    routes:
        p2p:
            path: /p2p/**
            sensitiveHeaders:
            serviceId: p2p-client${DEVLOPER_NAME:}
...

---
ribbon:
    restclient:
        enabled: true
    ConnectTimeout: 3000
    ReadTimeout: 60000
...
