Server:
    serviceName: Test1
    address: 127.0.0.1
management:
    security:
        enabled: false

---
spring:
    rabbitmq:
        host: localhost
        port: 5672
    cloud:
        bus:
            trace:
                enabled: true
...

---
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/

...

---
feign:
    hystrix:
        enabled: true
...