---
spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    cloud:
        bus:
            trace:
                enabled: true
        config:
            server:
                git:
                    uri: https://github.com/delacroix821026/p2p_config.git
                    cloneOnStart: true
                    force-pull: true
                    searchPaths: p2p*
                    username: 66039496@qq.com
                    password: philips1234
                health:
                    repositories:
                        p2p-config-server:
                            profiles: dev
                            label: master
                        p2p-config-server-branch:
                            name: p2p-config-server
                            profiles: prod
                            label: branch
    application:
        name: "@project.name@"
...

---
eureka:
    client:
        serviceUrl:
            defaultZone: http://eurekaserver1:1111/eureka/,http://eurekaserver2:1112/eureka/,http://eurekaserver3:1113/eureka/
        healthcheck:
            enabled: false
    instance:
        lease-expiration-duration-in-seconds: 40
        lease-renewal-interval-in-seconds: 20
        metadata-map:
            securit:
                user:
                    name: ${security.user.name}
                    password: ${security.user.password}
            management:
                context-path: ${management.context-path}
        statusPageUrl: http://${eureka.instance.hostname}:${server.port}/${management.context-path}/info
        healthCheckUrl: http://${eureka.instance.hostname}:${server.port}/${management.context-path}/health
...

---
management:
    security:
        enabled: true
        roles: SUPERUSER
    context-path: /manage
security:
    user:
        name: admin
        password: 123456
    basic:
        enabled: true
        path: ${management.context-path}
...
