---
spring:
    profiles: dev
    rabbitmq:
        host: 192.168.10.18
        port: 5672
        username: user_admin
        password: admin123%
    redis:
        host: 192.168.10.19
        port: 6379
        database: 0
...

---
spring:
    profiles: test
    rabbitmq:
        host: 10.0.1.42
        port: 5672
        username: user_admin
        password: admin123%
    redis:
        host: 10.0.1.49
        port: 6379
        database: 0
...

---
spring:
    profiles: prod
    rabbitmq:
        host: 10.0.1.46
        port: 5672
        username: user_admin
        password: admin123%Prod
    redis:
        host: 10.0.1.47
        port: 6379
        database: 0
...

---
spring:
    cloud:
        bus:
            trace:
                enabled: true
    datasource:
        name: dataSource
        url: ${datasource.url}
        username: ${datasource.username}
        password: ${datasource.password}
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 20
        maxIdle: 20
        minIdle: 0
        initialSize: 1
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 25200000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        maxPoolPreparedStatementPerConnectionSize: 33
        validationQuery: SELECT 1
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        filters: mergeStat

...

---
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

...

---
spring.batch.job.enabled: false
...

---
mybatis.config-location: classpath:mybatis-config.xml
...

---
logging:
    level:
        root: INFO
        com.newland.financial.p2p: TRACE
...

