---
spring:
    application:
        name: "@project.artifactId@"
    boot:
        admin:
            routes:
                endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
            notify:
                mail:
                    to: 66039496@qq.com
                    from: 66039496@qq.com
        #context-path: /manage
    mail:
        host: smtp.qq.com
        username: 66039496
        password: nxdgdhikcweobgbj
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
...

---
server:
    port: 6001
...

---
management:
    security:
        enabled: false
...

---
eureka:
    instance:
        hostname: bootadmin
        leaseRenewalIntervalInSeconds: 10
    client:
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: ${EUREKA_SERVICE_URL:http://localhost:1111}/eureka/
...
