---
spring:
    application:
        name: "@project.artifactId@"
    boot:
        admin:
            routes:
                endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
            notify:
                mail:
                    to: 66039496@qq.com
                    from: 66039496@qq.com
        #context-path: /manage
    mail:
        host: smtp.qq.com
        username: 66039496
        password: nxdgdhikcweobgbj
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
...

---
eureka:
    instance:
        metadata-map:
            user.name: ${security.user.name}
            user.password: ${security.user.password}
            management.context-path: ${management.context-path}
        statusPageUrl: http://${eureka.instance.hostname}:${server.port}/${management.context-path}/info
        healthCheckUrl: http://${eureka.instance.hostname}:${server.port}/${management.context-path}/health
        secure-health-check-url: http://${eureka.instance.hostname}:${server.port}/${management.context-path}/health
        leaseRenewalIntervalInSeconds: 10
    client:
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: ${EUREKA_SERVICE_URL:http://localhost:1111}/eureka/
...

---
management:
    #security:
        #enabled: true
        #roles: SUPERUSER
    context-path: /manage
security:
    user:
        name: admin
        password: 123456
    #basic:
        #enabled: true
        #path: ${management.context-path}
...
