---
spring:
    rabbitmq:
        host: 192.168.10.38
        port: 5672
        username: user_admin
        password: admin123%
    cloud:
        bus:
            trace:
                enabled: true
...

---
feign:
    hystrix:
        enabled: true
...