---
spring:
    rabbitmq:
        host: localhost
        port: 5672
    cloud:
        bus:
            trace:
                enabled: true
...

---
feign:
    hystrix:
        enabled: true
...