---
spring:
    rabbitmq:
        host: 192.168.10.38
        port: 5672
        username: user_admin
        password: admin123%
    cloud:
        bus:
            trace:
                enabled: true
    redis:
        host: 192.168.10.47
        port: 6379
        database: 0
    session:
        store-type: redis
...

---
feign:
    hystrix:
        enabled: true
...